### ISSUE TITLE
User can view a list of reviews

### ISSUE THREAD

**Issue by walston** [treezrppl2/project-one#3]
![wireframe](https://cloud.githubusercontent.com/assets/10055135/13446159/dafd2a20-dfc5-11e5-81ba-585bde3c07fc.png)
Though this is issue #3), it is referenced in this image as 2) due to a previous issue filed.

**Comment by walston** [comment]
There's a bug in the way tags are displayed
`var tagElement = document.createElement('span');
    obj.tags.forEach( function (tag){
      tagElement.appendChild(document.createTextNode(tag+' '))
      this.appendChild(tagElement);
    }, tags);`
a single tag element shouldn't contain all tags.

**Comment by treezrppl2** [comment]
i

**Comment by walston** [comment]
![User can see reviews by default](https://cloud.githubusercontent.com/assets/10055135/14541300/2235715a-023e-11e6-8068-0a46efab6efe.png)
